### ISSUE TITLE
Messages sent today and messages sent in the last week have the same number 

### ISSUE THREAD

**Issue by LaurabelleKay** [voldyman/strife#10]

**Comment by voldyman** [comment]
ah, looks like my state counter has a bug. I'll change it to a circular queue which rotates on write.

thanks for reporting the bug!

**Comment by voldyman** [comment]
Switched to ring buffer in https://github.com/voldyman/strife/commit/e84ac6cb0471195fcde40cfddef5e75f3b21aaab

will close this issue after confirming that it works.

**Comment by voldyman** [comment]
verified.
