### ISSUE TITLE
Ability to adjust volume

### ISSUE THREAD

**Issue by sohel101091** [voldyman/strife#4]
The bot should maybe start with a lower volume say 25. Then maybe add volume up/down for +/-5

**Comment by voldyman** [comment]
i don't know if i want to make it dynamically adjustable but maybe making it half of what it is right now would be enough.

note to self:
ffmpeg has `volume` flag which modified the volume relatively, maybe `volume=0.5` would be good enough.

**Comment by voldyman** [comment]
reduced volume, don't plan to make the volume adjustable
