### ISSUE TITLE
Ability to have a dynamic intro template

### ISSUE THREAD

**Issue by sohel101091** [voldyman/strife#9]
because new people who join the server don't know if the server is active (we hide all channels and message history unless they post an introduction), we need an intro message that contains info like 100 people online, 300 verified to be real people, 500 meetups to date, 1000 messages sent in the last day, 5k in the last week and so on
I guess the bot can take the template as an input and then fill it out with the info as required.

**Comment by voldyman** [comment]
Added welcome message:

```
Hello! Welcome to <server name>!
We are a group of <total members> people out of which <count> are online right now.
There are <people with real role> verified real members on this server, who meet regularly (when possible)
```

**Comment by voldyman** [comment]
next stage is keeping track of message counts and adding that to the message
